### ISSUE TITLE
QTA助手内置浏览器上能正常执行的demo，运行在QTA平台的虚拟机上报错

### ISSUE THREAD

**Issue by chxixix** [Tencent/QT4A#78]
在QT4A助手内置浏览器能正常执行的demo，运行在QTA平台的虚拟机上，第一次通过，第二、三次报错，报错点在打开浏览器这步，截图显示打开的浏览器页面混乱，部分含有第一次打开的页面内容

**Comment by drunkdream** [comment]
`QT4ABrowser`已提供清数据接口`clear_data`，`QT4W` `v2.0.66`版本默认在实例化`Browser`时会自动调用该接口
