### ISSUE TITLE
重打包生成的axml,resourceChunk缺少属性。

### ISSUE THREAD

**Issue by Willis-Chen** [Tencent/QT4A#84]
axml.py生成AXML时写入的reource_attr 只写入了EnumAttrType含有的属性。
如Android9上需要启动http时使用了networkSecurityConfig属性，但生成apk时未写入会导致android9上无法访问http。

简单的解决方法：
```python
for i, it in enumerate(self.res_map_chunk.res_map):
            attr_name = self.string_pool_chunk.string_list[i]
            # 如果apk的引用属性未在EnumAttrType则追加
            if (attr_name, it) not in EnumAttrType.list():
                setattr(EnumAttrType, attr_name.upper() + "_ATTR", (attr_name, it))
```

该方法是基于EnumAttrType的解决方式，不过个人感觉EnumAttrType的方式不是很好，希望作者看看如何更好的优化。

**Comment by drunkdream** [comment]
有包含`networkSecurityConfig`属性的应用吗，我这边测试没有这个属性，Android9上也是可以正常访问`http`页面的

**Comment by Willis-Chen** [comment]
android9系统上已经禁用明文http了，除非应用设置了android:usesCleartextTraffic="true"  或者networkSecurityConfig，否则app无法访问http。  重打包后的应用mainfest虽然有这个属性，但resouce arrt里缺少这个定义，导致这些开关不生效。      app打开http页面就没试过，但请求是走不通。

**Comment by drunkdream** [comment]
fixed in #87
